=== ghorwin/FMICodeGenerator/scripts/jsonimport/inputSchema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://who.cares/about-this.json",
    "title": "Python FMU Generator input",
    "description": "Input file of the Python FMU Generator",
    "type": "object",
    "properties": {
        "modelName": {
            "description": "Model name",
            "type": "string",
            "minLength": 1
        },
        "description": {
            "description": "Model description",
            "type": "string"
        },
        "fmuDestination": {
            "description": "Output path for the generated FMU",
            "type": "string"
        },
        "pythonSource": {
            "description": "Path of the input Python code",
            "type": "string",
            "minLength": 1
        },
        "spycicLocation": {
            "description": "Path to the Spycic library",
            "type": "string"
        },
        "pythonFunctions": {
            "description": "Python functions to be imported from the Python code",
            "type": "object",
            "propertyNames": {
                "enum": ["initME", "initCS", "updateME", "stepCS"]
            },
            "patternProperties": {
                "": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "pythonName": {
                                "description": "Name of the function in the Python code",
                                "type": "string"
                            },
                            "arguments": {
                                "description": "Array of function arguments",
                                "type": "array"
                            },
                            "output": {
                                "description": "Output variable for the function",
                                "type": "string"
                            }
                        },
                        "required": ["pythonName", "arguments", "output"],
                        "additionalProperties": false
                    }
                }
            }
        },
        "variables": {
            "description": "Array containing the variables of the model",
            "type": "array",
            "minItems": 1,
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "description": "Name of the variable",
                        "type": "string"
                    },
                    "valueRef": {
                        "description": "Value reference for the variable",
                        "type": "integer",
                        "minimum": 0
                    },
                    "variability": {
                        "description": "Variability tag for the variable",
                        "type": "string",
                        "enum": ["constant", "fixed", "tunable", "discrete", "continuous"]
                    },
                    "causality": {
                        "description": "Causality tag for the variable",
                        "type": "string",
                        "enum": ["input", "output", "local", "parameter", "calculatedParameter", "independent"]
                    },
                    "initial": {
                        "description": "Initial tag for the variable",
                        "type": "string",
                        "enum": ["exact", "approx", "calculated"]
                    },
                    "typeID": {
                        "description": "Type ID for the variable",
                        "type": "string",
                        "enum": ["Real", "Integer", "Boolean", "String"]
                    },
                    "startValue": {
                        "description": "Start value of the variable"
                    },
                    "description": {
                        "description": "Description of the variable",
                        "type": "string"
                    },
                    "unit": {
                        "description": "Physical unit of the variable",
                        "type": "string"
                    }
                },
                "required": ["name", "variability", "causality", "initial", "typeID"]
            }
        }
    },
    "required": ["modelName", "variables", "pythonSource", "pythonFunctions"]
}

=== ghorwin/FMICodeGenerator/scripts/tests/InconsistentFunctions/missingFunction.json
{
    "modelName": "myModel",
    "description": "Test case",
    "variables": [
        {
            "name": "tempIn",
            "variability": "continuous",
            "causality": "input",
            "initial": "approx",
            "typeID": "Real",
            "startValue": 271.5,
            "description": "",
            "unit": "K"
        },
        {
            "name": "tempOut",
            "variability": "continuous",
            "causality": "output",
            "initial": "approx",
            "typeID": "Real",
            "startValue": 271.5,
            "description": "",
            "unit": "K"
        }
    ],
	"pythonSource": "testCode.py",
    "pythonFunctions": {
        "initCS": [
            {
                "pythonName": "initialize",
                "arguments": [],
                "output": "tempOut"
            }
        ],
        "stepCS": [
            {
                "pythonName": "do_step",
                "arguments": ["not_a_variable", "stop_time"],
                "output": "tempOut"
            }
        ]
    }
}

=== ghorwin/FMICodeGenerator/scripts/tests/InconsistentVariables/multipleValueRef.json
{
    "modelName": "myModel",
    "description": "Test case",
    "variables": [
        {
            "name": "dummy",
            "variability": "continuous",
            "causality": "input",
            "initial": "approx",
            "typeID": "Real",
            "startValue": 271.5,
            "valueRef": 42,
            "description": "",
            "unit": "K"
        },
        {
            "name": "other",
            "variability": "discrete",
            "causality": "output",
            "initial": "exact",
            "typeID": "Integer",
            "startValue": 271,
            "valueRef": 42,
            "description": "",
            "unit": "M"
        }
    ],
	"pythonSource": "InconsistentFunctions/testCode.py",
    "pythonFunctions": {
        "initCS": [
            {
                "pythonName": "init",
                "arguments": [],
                "output": "tempOut"
            }
        ],
        "stepCS": [
            {
                "pythonName": "do_step",
                "arguments": ["startTime", "stop_time"],
                "output": "tempOut"
            }
        ]
    }
}

=== ghorwin/FMICodeGenerator/scripts/tests/InconsistentFunctions/mistypedArgument.json
{
    "modelName": "myModel",
    "description": "Test case",
    "variables": [
        {
            "name": "tempIn",
            "variability": "continuous",
            "causality": "input",
            "initial": "approx",
            "typeID": "Real",
            "startValue": 271.5,
            "description": "",
            "unit": "K"
        },
        {
            "name": "tempOut1",
            "variability": "continuous",
            "causality": "output",
            "initial": "approx",
            "typeID": "Real",
            "startValue": 271.5,
            "description": "",
            "unit": "K"
        },
        {
            "name": "tempOut2",
            "variability": "continuous",
            "causality": "output",
            "initial": "approx",
            "typeID": "Real",
            "startValue": 271.5,
            "description": "",
            "unit": "K"
        }
    ],
	"pythonSource": "testCode.py",
    "pythonFunctions": {
        "initCS": [
            {
                "pythonName": "init",
                "arguments": [],
                "output": "tempOut1"
            }
        ],
        "stepCS": [
            {
                "pythonName": "do_step",
                "arguments": ["start_time", "tempOut1"],
                "output": "tempOut2"
            }
        ]
    }
}

=== ghorwin/FMICodeGenerator/scripts/tests/InconsistentVariables/mistypedStartValueInteger.json
{
    "modelName": "myModel",
    "description": "Test case",
    "variables": [
        {
            "name": "dummy",
            "variability": "continuous",
            "causality": "input",
            "initial": "approx",
            "typeID": "Real",
            "startValue": 271.5,
            "description": "",
            "unit": "K"
        },
        {
            "name": "badlyTyped",
            "variability": "discrete",
            "causality": "output",
            "initial": "exact",
            "typeID": "Integer",
            "startValue": 1.2,
            "description": "",
            "unit": "M"
        }
    ],
	"pythonSource": "InconsistentFunctions/testCode.py",
    "pythonFunctions": {
        "initCS": {
            "pythonName": "init",
            "arguments": [],
            "output": "tempOut"
        },
        "stepCS": {
            "pythonName": "do_step",
            "arguments": ["start_time", "stop_time"],
            "output": "tempOut"
        }
    }
}

=== ghorwin/FMICodeGenerator/scripts/tests/WeatherSimC/WeatherSim.json
{
    "modelName": "WeatherSimC",
    "description": "A simple FMU that gives a temperature at a given time in a day.",
    "variables": [
        {
            "name": "tempOut",
            "variability": "continuous",
            "causality": "output",
            "initial": "approx",
            "typeID": "Real",
            "startValue": 271.5,
            "description": "",
            "unit": "K"
        }
    ],
	"pythonSource": "WeatherSim.py",
    "pythonFunctions": {
        "initCS": [
            {
                "pythonName": "init",
                "arguments": [],
                "output": "tempOut"
            }
        ],
        "stepCS": [
            {
                "pythonName": "do_step",
                "arguments": ["start_time", "stop_time"],
                "output": "tempOut"
            }
        ]
    },
    "spycicLocation": "path/to/spycic"
}

=== ghorwin/FMICodeGenerator/scripts/tests/InconsistentVariables/multipleDefinition.json
{
    "modelName": "myModel",
    "description": "Test case",
    "variables": [
        {
            "name": "definedTwice",
            "variability": "continuous",
            "causality": "input",
            "initial": "approx",
            "typeID": "Real",
            "startValue": 271.5,
            "description": "",
            "unit": "K"
        },
        {
            "name": "definedTwice",
            "variability": "discrete",
            "causality": "output",
            "initial": "exact",
            "typeID": "Integer",
            "startValue": 271,
            "description": "",
            "unit": "M"
        }
    ],
	"pythonSource": "InconsistentFunctions/testCode.py",
    "pythonFunctions": {
        "initCS": [
            {
                "pythonName": "init",
                "arguments": [],
                "output": "tempOut"
            }
        ],
        "stepCS": [
            {
                "pythonName": "do_step",
                "arguments": ["startTime", "stop_time"],
                "output": "tempOut"
            }
        ]
    }
}

=== ghorwin/FMICodeGenerator/scripts/tests/InvalidJSON/emptyVariables.json
{
    "modelName": "myModel",
    "variables": [
    ],
	"pythonSource": "InconsistentFunctions/testCode.py",
    "pythonFunctions": {
        "initCS": [
            {
                "pythonName": "init",
                "arguments": [],
                "output": "tempOut"
            }
        ],
        "stepCS": [
            {
                "pythonName": "do_step",
                "arguments": ["startTime", "stop_time"],
                "output": "tempOut"
            }
        ]
    }
}

=== ghorwin/FMICodeGenerator/scripts/tests/InconsistentVariables/mistypedStartValueString.json
{
    "modelName": "myModel",
    "description": "Test case",
    "variables": [
        {
            "name": "dummy",
            "variability": "continuous",
            "causality": "input",
            "initial": "approx",
            "typeID": "Real",
            "startValue": 271.5,
            "description": "",
            "unit": "K"
        },
        {
            "name": "badlyTyped",
            "variability": "discrete",
            "causality": "output",
            "initial": "exact",
            "typeID": "String",
            "startValue": false,
            "description": "",
            "unit": "M"
        }
    ],
	"pythonSource": "InconsistentFunctions/testCode.py",
    "pythonFunctions": {
        "initCS": [
            {
                "pythonName": "init",
                "arguments": [],
                "output": "tempOut"
            }
        ],
        "stepCS": [
            {
                "pythonName": "do_step",
                "arguments": ["startTime", "stop_time"],
                "output": "tempOut"
            }
        ]
    }
}
